// <auto-generated />
using System;
using GalacticDataExchange;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalacticDataExchange.Migrations
{
    [DbContext(typeof(DataDBContext))]
    partial class DataDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GalacticDataExchange.DataArtifact", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DataArtifactTypeID")
                        .HasColumnType("int");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawAlienText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DataArtifactTypeID");

                    b.ToTable("DataArtifacts");
                });

            modelBuilder.Entity("GalacticDataExchange.DataArtifactType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DataArtifactTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "A cube that stores data in a holographic matrix.",
                            Name = "Holographic Memory Cube"
                        },
                        new
                        {
                            ID = 2,
                            Description = "A sensor log that has been encrypted.",
                            Name = "Encrypted Sensor Log"
                        },
                        new
                        {
                            ID = 3,
                            Description = "An image of a relic that has been digitized.",
                            Name = "Digital Relic Image"
                        });
                });

            modelBuilder.Entity("GalacticDataExchange.DataArtifact", b =>
                {
                    b.HasOne("GalacticDataExchange.DataArtifactType", "DataArtifactType")
                        .WithMany()
                        .HasForeignKey("DataArtifactTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataArtifactType");
                });
#pragma warning restore 612, 618
        }
    }
}
