// <auto-generated />
using System;
using GalacticDataExchange.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalacticDataExchange.Shared.Migrations
{
    [DbContext(typeof(DataDBContext))]
    [Migration("20250419081209_DataArtifactLike")]
    partial class DataArtifactLike
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GalacticDataExchange.Shared.DataArtifact", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DataArtifactTypeID")
                        .HasColumnType("int");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawAlienText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DataArtifactTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("DataArtifacts");
                });

            modelBuilder.Entity("GalacticDataExchange.Shared.DataArtifactLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataArtifactID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.HasIndex("DataArtifactID", "UserID")
                        .IsUnique();

                    b.ToTable("DataArtifactLikes");
                });

            modelBuilder.Entity("GalacticDataExchange.Shared.DataArtifactType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DataArtifactTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "A cube that stores data in a holographic matrix.",
                            Name = "Holographic Memory Cube"
                        },
                        new
                        {
                            ID = 2,
                            Description = "A sensor log that has been encrypted.",
                            Name = "Encrypted Sensor Log"
                        },
                        new
                        {
                            ID = 3,
                            Description = "An image of a relic that has been digitized.",
                            Name = "Digital Relic Image"
                        });
                });

            modelBuilder.Entity("GalacticDataExchange.Shared.Sensor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Location = "Bridge of the Starfleet",
                            Name = "Thermo-1",
                            Type = "Temperature"
                        },
                        new
                        {
                            ID = 2,
                            Location = "Engineering Deck on the D'Vorik",
                            Name = "Baro-1",
                            Type = "Pressure"
                        },
                        new
                        {
                            ID = 3,
                            Location = "Cargo Bay of the Nebulon",
                            Name = "Hygro-1",
                            Type = "Humidity"
                        },
                        new
                        {
                            ID = 4,
                            Location = "Observation Deck of the Helix",
                            Name = "Lumina-1",
                            Type = "Light"
                        },
                        new
                        {
                            ID = 5,
                            Location = "Propulsion Chamber, Quasar Wing",
                            Name = "Vibro-1",
                            Type = "Vibration"
                        },
                        new
                        {
                            ID = 6,
                            Location = "Navigational Bridge, Delta Sector",
                            Name = "Motion-1",
                            Type = "Motion"
                        });
                });

            modelBuilder.Entity("GalacticDataExchange.Shared.SensorReading", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SensorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("SensorID");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("GalacticDataExchange.Shared.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GalacticDataExchange.Shared.DataArtifact", b =>
                {
                    b.HasOne("GalacticDataExchange.Shared.DataArtifactType", "DataArtifactType")
                        .WithMany()
                        .HasForeignKey("DataArtifactTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticDataExchange.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataArtifactType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GalacticDataExchange.Shared.DataArtifactLike", b =>
                {
                    b.HasOne("GalacticDataExchange.Shared.DataArtifact", "DataArtifact")
                        .WithMany("Likes")
                        .HasForeignKey("DataArtifactID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticDataExchange.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataArtifact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GalacticDataExchange.Shared.SensorReading", b =>
                {
                    b.HasOne("GalacticDataExchange.Shared.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GalacticDataExchange.Shared.DataArtifact", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("GalacticDataExchange.Shared.Sensor", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
